@Template.WebApi_HostAddress_Http = http://localhost:5105
@Template.WebApi_HostAddress_Https = https://localhost:7083

GET {{Template.WebApi_HostAddress_Http}}/api/v1/animals
Accept: application/json

###

GET {{Template.WebApi_HostAddress_Https}}/api/v1/animals
Accept: application/json

###
